### ISSUE TITLE
HotReloader 似乎不能正确的重载带自定义 Event 的插件

### ISSUE THREAD

**Issue by Taskeren** [Apisium/HotReloader#1]
```
[20:31:04 INFO]: [ElytraApi] Enabling ElytraApi v1.1.1-rc.1
[20:31:04 ERROR]: Error occurred while enabling ElytraApi v1.1.1-rc.1 (Is it up to date?)
java.lang.IllegalStateException: SuggestedLanguageChangedEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:612) ~[patched_1.17.1.jar:git-Paper-100]
        at cn.elytra.code.api.locale.LocaleService.setSuggestedLanguage(LocaleService.java:77) ~[?:?]
        at cn.elytra.code.api.locale.LocaleService.loadConfig(LocaleService.java:50) ~[?:?]
        at cn.elytra.code.api.ElytraApi.reloadLocale(ElytraApi.java:119) ~[?:?]
        at cn.elytra.code.api.ElytraApi.onEnable(ElytraApi.java:65) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Paper-100]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-100]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-100]
        at cn.apisium.hotreloader.Main.lambda$onCommand$1(Main.java:110) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Paper-100]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.1.jar:git-Paper-100]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-100]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[20:31:04 INFO]: [ElytraApi] Disabling ElytraApi v1.1.1-rc.1
[20:31:04 INFO]: [ElytraApi] elytra.api.plugin.disabled
[20:31:04 INFO]: [HotReloader]: Reload plugin successfully!
[20:31:04 INFO]: [ElytraApi] Enabling ElytraApi v1.1.1-rc.1
[20:31:04 ERROR]: Error occurred while enabling ElytraApi v1.1.1-rc.1 (Is it up to date?)
java.lang.IllegalStateException: SuggestedLanguageChangedEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:612) ~[patched_1.17.1.jar:git-Paper-100]
        at cn.elytra.code.api.locale.LocaleService.setSuggestedLanguage(LocaleService.java:77) ~[?:?]
        at cn.elytra.code.api.locale.LocaleService.loadConfig(LocaleService.java:50) ~[?:?]
        at cn.elytra.code.api.ElytraApi.reloadLocale(ElytraApi.java:119) ~[?:?]
        at cn.elytra.code.api.ElytraApi.onEnable(ElytraApi.java:65) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Paper-100]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-100]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-100]
        at cn.apisium.hotreloader.Main.lambda$onCommand$1(Main.java:110) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Paper-100]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.1.jar:git-Paper-100]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-100]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[20:31:04 INFO]: [ElytraApi] Disabling ElytraApi v1.1.1-rc.1
[20:31:04 INFO]: [ElytraApi] elytra.api.plugin.disabled
[20:31:04 INFO]: [HotReloader]: Reload plugin successfully!
[20:31:04 INFO]: [ElytraApi] Enabling ElytraApi v1.1.1-rc.1
[20:31:04 ERROR]: Error occurred while enabling ElytraApi v1.1.1-rc.1 (Is it up to date?)
java.lang.IllegalStateException: SuggestedLanguageChangedEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:612) ~[patched_1.17.1.jar:git-Paper-100]
        at cn.elytra.code.api.locale.LocaleService.setSuggestedLanguage(LocaleService.java:77) ~[?:?]
        at cn.elytra.code.api.locale.LocaleService.loadConfig(LocaleService.java:50) ~[?:?]
        at cn.elytra.code.api.ElytraApi.reloadLocale(ElytraApi.java:119) ~[?:?]
        at cn.elytra.code.api.ElytraApi.onEnable(ElytraApi.java:65) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Paper-100]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-100]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-100]
        at cn.apisium.hotreloader.Main.lambda$onCommand$1(Main.java:110) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Paper-100]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.1.jar:git-Paper-100]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-100]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[20:31:04 INFO]: [ElytraApi] Disabling ElytraApi v1.1.1-rc.1
[20:31:04 INFO]: [ElytraApi] elytra.api.plugin.disabled
[20:31:04 INFO]: [HotReloader]: Reload plugin successfully!
>
>


```

**Comment by ShirasawaSama** [comment]
@Taskeren 请下载最新版的的试一下

**Comment by Taskeren** [comment]
哇，这效率也太高了！明天试试。

**Comment by ShirasawaSama** [comment]
@Taskeren 问题有解决吗

**Comment by Taskeren** [comment]
并没有，还是一样的错误
